### ISSUE TITLE
[Rector] Add support for depends

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/drift#14]
A new core feature for phpunit depends has been added, so we need a new rector is needed.

https://github.com/pestphp/pest/pull/103

**Comment by owenvoke** [comment]
I'd love to take a look at this if I get time. 👍 But if someone else wants to, don't hesitate to add it. 🙂

**Comment by olivernybroe** [comment]
@owenvoke You can take a look at this one :) Just write to me if you need any help 👍
