### ISSUE TITLE
Add support for String Interpolation when migrating helper methods

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/drift#20]
Right now we have a test which fails because we are trying to migrate a class method to a pest helper method. 

However the original class method was used in string interpolation which is not supported by functions, so the string interpolation has to be split up, so it can use the pest helper.

Example:
We have the following php class
```php
class MethodStringInterpolationTest extends TestCase
{
    private function alwaysTrueHelper()
    {
        return "true";
    }

    public function testMethod()
    {
        "{$this->alwaysTrueHelper()} works";
    }
}
```
Which should be converted to 
```
function alwaysTrueHelper()
{
    return "true";
}
test('testMethod', function () {
    alwaysTrueHelper() . " works";
});
```

Because doing ` "{alwaysTrueHelper()} works";` is not valid php code.

Fixture file:
https://github.com/pestphp/drift/blob/master/tests/fixtures/PHPUnit/ClassMethod/HelperMethodRector/phpunit_method_to_pest_helper_used_in_string_interpolation.php.inc

**Comment by olivernybroe** [comment]
Hey @TomasVotruba, you told me a while ago to tag you with a failing test case for string interpolation conversion 👍 

Any pointers on how to solve this would be really nice, we have a failing test in our testsuite right now for this.

**Comment by TomasVotruba** [comment]
Hi, could you link me to the Rector rule + failing line in CI?

**Comment by olivernybroe** [comment]
Sure.

- [failing build](https://github.com/pestphp/drift/runs/897364199)
- [Test file](https://github.com/pestphp/drift/blob/master/tests/Rectors/PHPUnit/ClassMethod/HelperMethodRectorTest.php)
- [Rector rule](https://github.com/pestphp/drift/blob/master/src/PHPUnit/ClassMethod/HelperMethodRector.php)
- [Method in Rector rule which should be responsible for this
](https://github.com/pestphp/drift/blob/master/src/PHPUnit/ClassMethod/HelperMethodRector.php#L101-L132)

**Comment by TomasVotruba** [comment]
Thank you. I've used all the links :)
