### ISSUE TITLE
Write docs for CLI tool

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/drift#26]
We have a small CLI tool which has no documentation at all. 

We should write a small section in the readme file on how to use it.

**Comment by owenvoke** [comment]
Do we want to use the README? Or just use the ones that are on the website?
https://pestphp.com/docs/guides/drift

Obviouslt those docs are just a start and should be updated with additional info when ready. :+1:

**Comment by olivernybroe** [comment]
I think the readme should contain link to the website and then just a quick info on what this tool is. 😄

**Comment by DannyvdSluijs** [comment]
With changes added in https://github.com/pestphp/drift/commit/8b8dd0dd2701b628217267f1822e6618d6223b05#diff-04c6e90faac2675aa89e2176d2eec7d8 it seems the readme already mentions what it does and ins linking to the Pest documentation. Unless you would like to have the usage from the docs copied into the Readme (and get out of sync from the site) I guess this issue can be closed?
