### ISSUE TITLE
bug: "config/phpunit-to-pest.yml" was not found

### ISSUE THREAD

**Issue by nunomaduro** [pestphp/drift#31]
Got this error just after a fresh installation of drift. Any ideas?

<img width="895" alt="Screenshot 2020-08-27 at 22 33 32" src="https://user-images.githubusercontent.com/5457236/91492106-57eb8980-e8b5-11ea-9d56-733341a54a67.png">

**Comment by owenvoke** [comment]
Rector now uses PHP for configuration instead of YAML. So these references should be updated:
https://github.com/pestphp/drift/blob/master/src/RectorRunner.php#L20

**Comment by nunomaduro** [comment]
@owenvoke @olivernybroe Maybe we can lock the rector version to avoid this kind of things?

**Comment by olivernybroe** [comment]
@nunomaduro No need, what @owenvoke means is that rector recommends PHP configs instead of YAML, so we made the change. We just forgot to update everything.

We really need some tests that checks the whole application and not just the rectors.
