### ISSUE TITLE
Following Drift installation steps doesn't work with Pest 0.3.1 

### ISSUE THREAD

**Issue by DannyvdSluijs** [pestphp/drift#37]
Hi all and many thanks for trying to get such a transformation package available.

While following the basic installations steps from https://pestphp.com/docs/installation/ followed by https://pestphp.com/docs/guides/drift/. I end up with an error `Your requirements could not be resolved to an installable set of packages.` It seems there is some conflicts going on.

_Full error from running `composer require pestphp/drift --dev --update-with-all-dependencies`:_
```
  Problem 1
    - pestphp/pest v0.2.x-dev conflicts with pestphp/pest-plugin-init[v0.3.0].
    - pestphp/pest v0.2.x-dev conflicts with pestphp/pest-plugin-init[v0.3.0].
    - pestphp/pest v0.2.x-dev conflicts with pestphp/pest-plugin-init[v0.3.0].
    - pestphp/drift dev-master requires pestphp/pest ^0.2 -> satisfiable by pestphp/pest[v0.2.x-dev].
    - Installation request for pestphp/drift dev-master -> satisfiable by pestphp/drift[dev-master].
    - Installation request for pestphp/pest-plugin-init (locked at v0.3.0) -> satisfiable by pestphp/pest-plugin-init[v0.3.0].


```
_Composer.json and Composer.lock created can be found at https://gist.github.com/DannyvdSluijs/92f1b30ba65de5122b5285fa443ec0eb_

**Comment by owenvoke** [comment]
Ah, looks like Drift is the only plugin that isn't on v0.3 yet. 👍🏻  I should be able to resolve this tomorrow or some time this weekend hopefully. It also converts to the old pre-expectation API. So that will need to be resolved as well.

**Comment by DannyvdSluijs** [comment]
I've created PR #38 to bump to require version `^0.3` of drift. Didn't see any failures on the tests though.

**Comment by olivernybroe** [comment]
Further analysis shows that we could easily remove the dependency to pest. 

This should solve this problem for good :)
