### ISSUE TITLE
[Rector] Remove $this 

### ISSUE THREAD

**Issue by olivernybroe** [pestphp/drift#4]
Create a new rector which is responsible for removing `$this` on methods that doesn't need them.

```php 
it('asserts true is true', function () {
    $this->assertTrue(true);

    // Same as
    assertTrue(true);
});
```

The reason for using a new rector is so we can optionally enable/disable it and decouple it from the base rector which is about just refactoring to pest test cases, not making them nicer.

[Pest docs](https://pestphp.com/docs/assertions/)

**Comment by owenvoke** [comment]
I guess this is no longer relevant in v0.3 of Pest. 🤔

The `expect()` API is now preferred (although the [Global Assertions](https://github.com/pestphp/pest-plugin-global-assertions) does exist as a polyfill). Obviously the functions are also still available directly in PHPUnit [under the `PHPUnit\Framework\*` namespace](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert/Functions.php).

**Comment by olivernybroe** [comment]
@owenvoke So you are thinking we should have a rector that converts to the `expect` api?

**Comment by owenvoke** [comment]
Probably not as it doesn't map 1 to 1 with existing assertions. But could do for some of them. 🤷🏻 I was more saying that this issue probably isn't really necessary now.

**Comment by olivernybroe** [comment]
Alright, let's close it then 👍
